name: ChessCoach
options:
  bundleIdPrefix: com.chesscoach
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
packages:
  ChessKitEngine:
    path: LocalPackages/chesskit-engine
  ChessboardKit:
    path: LocalPackages/ChessboardKit
  GRDB:
    url: https://github.com/groue/GRDB.swift.git
    from: "7.0.0"
targets:
  ChessCoach:
    type: application
    platform: iOS
    sources:
      - ChessCoach
    resources:
      - path: ChessCoach/Resources/Openings
        buildPhase: resources
      - path: ChessCoach/Resources/Qwen3-4B-Q4_K_M.gguf
        buildPhase: resources
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 2DUT9WB762
        PRODUCT_BUNDLE_IDENTIFIER: com.marklifson-chesscoach.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
      configs:
        Debug:
          STOREKIT_CONFIGURATION: ChessCoach.storekit
    dependencies:
      - package: ChessKitEngine
      - package: ChessboardKit
      - package: GRDB
      - framework: Frameworks/llama.xcframework
        embed: true
  ChessCoachTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - ChessCoachTests
    dependencies:
      - target: ChessCoach
    settings:
      base:
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
